return {
  'fladson/vim-kitty', -- syntax highlighting for kitty config
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
      local configs = require('nvim-treesitter.configs')
      configs.setup({
        sync_install = false,
        highlight = { enable = true },
        indent = { enable = true },
        ensure_installed = {
          'bash',
          'c',
          'cpp',
          'css',
          'diff',
          'dockerfile',
          'elm',
          'git_config',
          'git_rebase',
          'gitattributes',
          'gitcommit',
          'gitignore',
          'go',
          'gomod',
          'gosum',
          'gotmpl',
          'gpg',
          'graphql',
          'html',
          'ini',
          'javascript',
          'jq',
          'jsdoc',
          'json',
          'json5',
          'jsonc',
          'jsonnet',
          'just',
          'kdl',
          'kotlin',
          'lua',
          'luadoc',
          'make',
          'markdown',
          'markdown_inline',
          'meson',
          'nix',
          -- 'norg', -- disabled because of compilation error
          'ocaml',
          'prisma',
          'python',
          'query',
          'regex',
          'roc',
          'rust',
          'scss',
          'sql',
          'svelte',
          'templ',
          'toml',
          'tsx',
          'typescript',
          'vim',
          'vimdoc',
          'xml',
          'yaml',
        },
      })
    end,
  },
}
